### ISSUE TITLE
cannot load such file -- haml/html (LoadError)

### ISSUE THREAD

**Issue by zsan** [c0untd0wn/erb2slim#2]
I just ran gem install erb2slim and then i got an error

<pre>
/home/zak/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:106:in `require': cannot load such file -- haml/html (LoadError)
        from /home/zak/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:106:in `require'
        from /home/zak/.rvm/gems/ruby-2.0.0-p0/gems/erb2slim-0.0.1/lib/erb2slim.rb:2:in `<top (required)>'
        from /home/zak/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `require'
        from /home/zak/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:110:in `rescue in require'
        from /home/zak/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:35:in `require'
        from 2slim.rb:8:in `<main>'
</pre>

I looked at erb2slim.rb, i saw in line 2:

<pre>
require 'haml/html'
</pre>

and then i just change the line to

<pre>
require 'html2haml/html'
</pre>

And the error just gone..

**Comment by ic** [comment]
Just seeing this issue now. And just 6 year old! Fixed in #4 ...
