### ISSUE TITLE
`NoMethodError` raised for `Ruby 3.2.0`

### ISSUE THREAD

**Issue by akoskovacs** [c0untd0wn/erb2slim#5]
Hey! I got an exception when attempting to run `erb2slim` on a Rails 7 application:
```sh
$ erb2slim app/views/ --trace
/home/akos/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/html2slim-0.2.0/lib/html2slim/converter.rb:17:in `initialize': undefined method `exists?' for File:Class (NoMethodError)

      erb = File.exists?(file) ? open(file).read : file
                ^^^^^^^^
Did you mean?  exist?
	from /home/akos/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/html2slim-0.2.0/lib/html2slim.rb:9:in `new'
	from /home/akos/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/html2slim-0.2.0/lib/html2slim.rb:9:in `convert!'
	from /home/akos/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/html2slim-0.2.0/lib/html2slim/command.rb:98:in `_process'
	from /home/akos/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/html2slim-0.2.0/lib/html2slim/command.rb:66:in `block in process!'
	from /home/akos/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/html2slim-0.2.0/lib/html2slim/command.rb:66:in `each'
	from /home/akos/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/html2slim-0.2.0/lib/html2slim/command.rb:66:in `process!'
	from /home/akos/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/html2slim-0.2.0/lib/html2slim/command.rb:15:in `run'
	from /home/akos/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/html2slim-0.2.0/bin/erb2slim:7:in `<top (required)>'
	from /home/akos/.rbenv/versions/3.2.0/bin/erb2slim:25:in `load'
	from /home/akos/.rbenv/versions/3.2.0/bin/erb2slim:25:in `<main>'

```

Versions:

```sh
$ rails -v
Rails 7.0.4.2
```
```sh
$ erb2slim -v
erb2slim 0.2.0
```

**Comment by bellps** [comment]
@akoskovacs Any solutions? I'm facing the same issue :/

**Comment by akoskovacs** [comment]
@bellps No, I don't have anything, unfortunately.

**Comment by fvue** [comment]
See: https://github.com/slim-template/html2slim/issues/45
